# 2.3.2 - Output pada Python (hal. 27-28)

print("===== 2.3.2 - Output pada Python =====")
print("> Latihan Input & Output")
print("=+=+=+=+ Data Diri Mahasiswa =+=+=+=+")
nim = input("NIM: ")
nama = input("Nama Lengkap: ")
jurusan = input("Jurusan: ")
alamat = input("Alamat: ")

print("="*10+" Hasil Cetak "+"="*10)
print("Hasil cetak data diatas adalah")
print("Nim : "+str(nim))
print("Nama : "+str(nama))
print("Jurusan : "+str(jurusan))
print("Alamat : "+str(alamat))